spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ilussencio.duckdns.org:3306/prontuario_plus?useTimezone=true&serverTimezone=UTC
    #url: jdbc:mysql://localhost:3306/prontuario_plus?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  springdoc:
    paths-to-match:
      - /api/v1/**
  swagger-ui:
    use-root-path: true
server:
  port: 9090
  servlet:
    context-path: /api/v1